name: Publish to Docker Hub (Daily)

on:
  push:
    branches: [ master ]

jobs:
  docker-daily-build:
    name: Build docker image
    strategy:
      matrix:
        include:
          - arch: 'amd64'
            dockerfile: 'Dockerfile'

          # - arch: 'arm64'
          #   dockerfile: 'Dockerfile.aarch64'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: "${{ github.sha }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Get release info
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          branch: true
          prefix: v
          prefixRegex: "[vV]?"

      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU
        with:
          platforms: arm64
        if: ${{ matrix.arch == 'arm64' }}

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - name: Log into docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

        # Disabled provenance for now, until it works with docker manifest create.
        # The manifest list produced by the new feature is incompatible with the
        # expected format used in the docker manifest create command.
      - name: Build and Push the Docker image
        run: docker buildx build . --file ${{ matrix.dockerfile }} --tag ${{ secrets.DOCKER_REPO }}:daily-${{ matrix.arch }} --platform linux/${{ matrix.arch }} --build-arg version=${{ steps.release_info.outputs.version }} --build-arg channel=dev --build-arg commit=${{ github.sha }} --push --provenance=false

  docker-daily-push_manifest:
    needs: docker-daily-build
    name: Push combined tag for both images
    runs-on: ubuntu-latest

    steps:
      - name: Log into docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifest
        run: docker manifest create ${{ secrets.DOCKER_REPO }}:daily --amend ${{ secrets.DOCKER_REPO }}:daily-amd64

      - name: Push manifest
        run: docker manifest push ${{ secrets.DOCKER_REPO }}:daily
